# see https://github.com/marketplace/actions/sonarcloud-scan-for-c-and-c#usage
name: Sonar Check

on:
  push:
    branches:
      - dev
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    if: github.repository == 'emsesp/EMS-ESP32'
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: bw-output
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@master
      - name: Run Build Wrapper
        run: build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} make all
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands="${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
            
