name: "Mark or close stale issues and PRs"
 
on:
  schedule:
  - cron: "30 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 30
        days-before-close: 5
        stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment otherwise this will be closed in 5 days."
        stale-pr-message: "This PR has been automatically marked as stale because there has been no activity in last 30 days. It will be closed if no further activity occurs. Thank you for your contributions."
        close-issue-message: "This issue was closed because it has been stalled for 5 days with no activity."
        close-pr-message: "This PR was automatically closed because of being stale."
        stale-pr-label: "stale"
        stale-issue-label: "stale"
        exempt-issue-labels: "bug,enhancement,pinned,security"
        exempt-pr-labels: "bug,enhancement,pinned,security"
